syntax on
set hlsearch
set smartcase
set ic
set incsearch
set history=700
set autoread
set nobackup
set nowb
set noswapfile
set tabstop=4
set shiftwidth=4
set winminheight=0
set t_Co=256
set laststatus=2
set ruler
set showmode
set viminfo=%,'50,\"100,:100,n~/.viminfo
