source ~/.config/base16-shell/scripts/base16-grayscale-dark.sh

export EDITOR=vim
export PATH=$HOME/.bin:/sbin:$PATH
HISTSIZE=1000
HISTFILESIZE=2000

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash
[ -f /usr/share/fzf/completion.bash ] && source /usr/share/fzf/completion.bash
