#!/bin/sh

#jif test -e /usr/bin/xmodmap; then
#j  if test -e .Xmodmap; then
#j    xmodmap .Xmodmap
#j  fi
#jfi

#setxkbmap -option 'ctrl:swap_rwin_rctl' -layout 'us(mac)'
setxkbmap -option 'caps:super' -layout 'us(mac)'

xrdb -load ~/.Xresources

dunst -config "$HOME"/.config/dunst/dunstrc &

# Start WM
xsetroot -cursor_name left_ptr
xmonad 2> .logs/xmonad.err > .logs/xmonad.log
