#!/bin/sh

setxkbmap -option compose:rctrl -layout 'us(mac)'

xrdb -load ~/.Xresources

dunst -config "$HOME"/.config/dunst/dunstrc &

# Start WM
xsetroot -cursor_name left_ptr
xmonad 2> .logs/xmonad.err > .logs/xmonad.log
